# Generated by Django 3.1.6 on 2021-02-15 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='Please enter your first name', max_length=200)),
                ('last_name', models.CharField(default='Please enter your last name', max_length=200)),
                ('dob', models.DateField(default='Please enter your DOB')),
                ('highest_qualification', models.CharField(default='Please enter your highest qualification', max_length=200)),
                ('stream', models.CharField(default='Enter your stream', max_length=200)),
                ('ssc', models.IntegerField(default='Enter your 10th marks')),
                ('inter', models.IntegerField(default='enter your 12 th marks')),
                ('bachelor', models.IntegerField(null=True)),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('eye_sight', models.FloatField(null=True)),
                ('disorder', models.CharField(max_length=200, null=True)),
                ('nationality', models.CharField(max_length=200)),
            ],
        ),
    ]
